### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by xtedx** [google-developer-training/android-basics-kotlin-dessert-clicker-app#17] opened 2021-03-27 03:50 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

**In which task and step of the codelab can this issue be found?**
module 4 Stages of the activity lifecycle
step 4/5 of the codelab

**Describe the problem**
formatting issues.
the start of step 5 is part of step 4's end , just after *transaction too large error.*

it should be  as a new paragraph/numbered list
<img width="1227" alt="Screen Shot 2021-03-27 at 2 46 00 pm" src="https://user-images.githubusercontent.com/13181908/112709226-85f88100-8f0b-11eb-9ee7-5acfd659d271.png">

**Comment by danielslabo** [comment] 2021-04-11 16:58
This is a duplicate of issue #15

**Comment by osuleymanova** [comment] 2021-10-27 22:18
@xtedx 
Thank you for informing us about this issue. It's fixed.

**Closed as completed by osuleymanova** 2021-10-27 22:18 UTC
