### ISSUE TITLE
Android Basics: Activity Lifecycle - Step 5 needs indentation in "Use onSaveInstanceState() to save bundle data"

### ISSUE THREAD

**Issue by d8vd** [google-developer-training/android-basics-kotlin-dessert-clicker-app#26] opened 2021-06-14 01:49 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?authuser=3&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fauthuser%3D3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

**In which task and step of the codelab can this issue be found?**
Use onSaveInstanceState() to save bundle data

Step 5 needs indentation.

**Describe the problem**
The instructions are all indented, except for #5.
<img width="770" alt="Screen Shot 2021-06-13 at 6 47 24 PM" src="https://user-images.githubusercontent.com/71815877/121829666-0790bd00-cc78-11eb-92de-30ef08e4bcc7.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-10-27 22:23
Duplicate of #15, #17

**Comment by osuleymanova** [comment] 2021-10-27 22:24
@d8vd 
Thank you for reaching out to us. The issue is fixed and published.

**Closed as completed by osuleymanova** 2021-10-27 22:24 UTC
